//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermissionBaseRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public int ID { get; set; }
        public int PageID { get; set; }
        public int RoleID { get; set; }
        public string Action { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Role Role { get; set; }
    }
}
